---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    openshift.io/user-monitoring: 'true'
    app.kubernetes.io/name: payments
    app.kubernetes.io/instance: payments
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: payment-processor
