---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: payments
type: Opaque
stringData:
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: reporting-db
  namespace: payments
type: Opaque
stringData:
  PGUSER: reporting
  PGPASSWORD: reporting123
